### ISSUE TITLE
Blacklist or "select all" function for Whitelist

### ISSUE THREAD

**Issue by njascgil** [aviraxp/AdBlocker_Reborn#11]
Hi!
I try to keep adblockers enabled for a minimum number of apps (for compatibility reasons). For example, I found out that the app FeedMe is slowed down a lot by this adblocker and it doesn't even have ads...

Would you consider adding a blacklist/whitelist mode selector? (Although I think a "select all" button for the whitelist would be equally effective...)
Thanks!

[edit: typo/grammar]

**Comment by rogertpiven** [comment]
:thumbsup:

**Comment by aviraxp** [comment]
Added.
