### ISSUE TITLE
will there be..

### ISSUE THREAD

**Issue by rogertpiven** [aviraxp/AdBlocker_Reborn#13]
.. URL filtering

.. fetched object dimension filtering

.. simple regex examples to do layman wildcard filtering?   *lytic* , *crash*

.. :hotsprings: 

.. smarter traffic logging to highlight servers with slower responses (3rd party ads) than rest of traffic

.. spoofing http response code 200   [mwahaha] 
.... i think the solution to waze ads both inline searches and on map callouts 

ftw

**Comment by aviraxp** [comment]
I have tried regex but that consume too many resources.

URL filtering is in process.

As for others, I will not do that.
