### ISSUE TITLE
Support for YouTube ads?

### ISSUE THREAD

**Issue by acsway878787** [aviraxp/AdBlocker_Reborn#16]
As I mentioned above, does it support YouTube ads?
And I hope there will be Blacklist in further version, because some people would like to block specific apps, not almost apps.

**Comment by aviraxp** [comment]
No, and never.

For blacklists, there will be.

**Comment by sm4rk0** [comment]
@acsway878787 I'm using [NewPipe](https://github.com/TeamNewPipe/NewPipe) for viewing YT videos and there are no ads. It's actively developed and new features are added frequently.
