### ISSUE TITLE
不能过滤魔趣中心的广告

### ISSUE THREAD

**Issue by ivysrono** [aviraxp/AdBlocker_Reborn#2]
0.1b
MK60.1-161118-RELEASE

**Comment by aviraxp** [comment]
魔趣中心是这样的，本来是普通的谷歌广告，但是他们做了混淆，导致无法正确地hook上。现在没有很好的想法，你可以把魔趣中心(什么Helper)那个app发来看看。

**Comment by aviraxp** [comment]
请测试0.1c。

**Comment by ivysrono** [comment]
@aviraxp 0.1c广告会被隐藏。
第一次进入后屏幕会变暗，其实就是广告出现但被隐藏了，按下后退就好了。
不知是否还有改进空间。无论如何，非常感谢。

**Comment by ivysrono** [comment]
0.2
161126 RELEASE
广告再现。

**Comment by aviraxp** [comment]
我把魔趣的特别处理去掉了，因为那个办法太脏。我再想想别的办法。
