### ISSUE TITLE
建议增加应用搜索/过滤功能

### ISSUE THREAD

**Issue by StrollStars** [aviraxp/AdBlocker_Reborn#21]
“应用黑/白名单”会枚举系统中的所有应用，可是要其中找出指定的应用非常困难。
建议增加应用的搜索/过滤功能，以方便快速选择想要的应用。

**Comment by aviraxp** [comment]
这么说吧，如果不导入v7库，是没有搜索这个功能的。而如果导入v7库，整个界面要重写。所以暂时不考虑这个。

**Comment by StrollStars** [comment]
那能够方便实现显示应用图标或者导出当前排序的应用列表吗？
现在的排序方式好像是优先应用名，没有应用名的按包名，然后复选框在名称中间，比较难找。
PS：建议复选框在多行名称的第一行。

**Comment by aviraxp** [comment]
这个可以。
