### ISSUE TITLE
pls fix

### ISSUE THREAD

**Issue by BinoWassabi** [aviraxp/AdBlocker_Reborn#6]
youtube history is affected cant record history

**Comment by aviraxp** [comment]
Very sorry for this, the hosts now is not stable enough and there might be some false-positives. I will fix it today and upload a new version if time permits.

**Comment by BinoWassabi** [comment]
i  uncheck the enable services blocking its ok now thx for the reply though

**Comment by aviraxp** [comment]
Nope, it has nothing to do with services blocking. I will release a new version today with the fixes.

**Comment by BinoWassabi** [comment]
oh ok
